apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: antoinedespres/simona-auth-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/simona_account_service
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-service
spec:
  selector:
    matchLabels:
      app: housing-service
  template:
    metadata:
      labels:
        app: housing-service
    spec:
      containers:
        - name: housing-service
          image: antoinedespres/simona-housing-service
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/simona_housing_service
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: none
            - name: RENTAL_SERVICE_BASE_URL
              value: rental-service.default.svc.cluster.local:8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-service
spec:
  selector:
    matchLabels:
      app: rental-service
  template:
    metadata:
      labels:
        app: rental-service
    spec:
      containers:
        - name: rental-service
          image: antoinedespres/simona-rental-service
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/simona_rental_service
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - '*'
