
gateway:
  host: localhost
  url: http://${gateway.host}:8080

server:
  port: 8082

spring:
  application:
    name: housing-service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/