gateway:
  host: localhost
  url: http://${gateway.host}:8080

server:
  port: 8082

spring:
  application:
    name: housing-service

eureka:
  # Avoid DNS error with Eureka
  # see: https://stackoverflow.com/a/65492040
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
