server:
  port: 8080

jwt:
  secret: hellodarknessmyoldfriendhellodarknessmyoldfriend

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/rental/api/v1/**
          filters:
            - JwtFilter
            - RewritePath=/rental/api/v1/(?<segment>.*), /$\{segment}

        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/housing/api/v1/**
          filters:
            - JwtFilter
            - RewritePath=/housing/api/v1/(?<segment>.*), /$\{segment}

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/api/v1/**
          filters:
            - RewritePath=/auth/api/v1/(?<segment>.*), /$\{segment}

eureka:
  # Avoid DNS error with Eureka
  # see: https://stackoverflow.com/a/65492040
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Aggregate microservices API swagger docs
# See the sample config: https://stackoverflow.com/a/74923329
springdoc:
  swagger-ui:
    urls:
      - url: /housing/api/v1/v3/api-docs
        name: Housing-service
      - url: /rental/api/v1/v3/api-docs
        name: Rental-service
      - url: /auth/api/v1/v3/api-docs
        name: Auth-service
